# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'firebase_demo' do

end

target 'firebase_demoTests' do

end

pod 'Firebase', '>= 2.5.0'